# Generated by Django 3.1 on 2020-08-31 21:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import syllabi.models
import syllabi.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please provide the term, year and Professor', max_length=75)),
                ('file', models.FileField(help_text='Please keep the size of file below 2MiB', max_length=300, upload_to=syllabi.models.syllabus_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), syllabi.validators.file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('anonymous', models.BooleanField(default=False, help_text='If anonymous is checked, your name will be hidden.', max_length=10)),
                ('link', models.URLField(help_text='Please provide the link to the syllabus', max_length=250)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_course', to='course.course')),
                ('likes', models.ManyToManyField(blank=True, default=0, related_name='syllabus_likes', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_university', to='university.university')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
